language: java
jdk:
  - openjdk11

env:
  global:
    secure:
    - "Lfmq8OKMbRTLFEI1c4VGTSvbwpvMzrAH79PdwX3/iELAGBvSoQLW3Rqz+//TcJWKOgOVmHSpUVDcR8GOOoc5hQ5Vq3NTNKCihGRTEtGs641vsg8dx6jHR/TjcN3Tsopwb4BwXOOanLeNMiuRUSh3BbU9zGT4UBL3/03BKX0dXctRy+hK+zgEm/807KmZ/PNQQOVQsZc/+3rZU009lhgCRe7jsRtftRrO5juQDoYnt3uXorCuWw4r7rtvTzGgXJMhbp4jgLzQKHigqsFoESN+9i4yqrpHixKgpgFCBHo/bJZIA3zFdy85+ENKuMrUeJKultJEDr3VdxyyqylE5I11SFZ4EO72FrGy4hlr71Oj9qV4RYWZQwBR9BLcpPbkbFv91BaMYE2R3huKJH49staKG2lLx1munKU/OtJJsnXvBrNtsPcRlo2oUQ0F5l7Uno+v8CMy7M+p2KAzKCNfuAA7CYIaESovWxPD/gybf9GziilFfTfM7yCqMWtZoXxtySYn2V/peRx1JeWtosMRDM0hFExGTpGqpWj7TpdgxOCkudqMTgtQPUqZilWsGfuSh7rT2Q7ydSXYYvAXP5dCUV3xtnfdrFDes7vt+1SI/Brh5p7zyFgc3qbi8fFJYqnYQJbJgsbIhATkgCdZizigPUIyhLlImEVgMCgHciz8IaJWW0s="
    - "XIrzNtuvDJ7fSy66QhXGNomyydAXLiltlk646qsCeCEoHHxofHeJfHuzQeXh5EAQBPrEYhZV9Sj2JZka5QpP/sY2gBKEzGh402hzwbQemsYVDpfvhaqoT3Je3Pa6wqaU9jpjCZB6aGNd9e9M8CpyBU1vkIRd0exeO0oO2zi2dZx85YSWTO/lPyqZ0SWDmOsV9EykqnbhWqVW+MdzQlCTbvO6NX5CGqO01N4bdIvK8TCSHeGTpYuE/KLk3ztOg2Tq8kF23SgA/ve4EMSg9mGpcYCaQ/UDm2wo4tYZBQA2EBXYbXz2KWBYY7+KVe+DSIMJOy5or3SDUQos2G+rhw0uY3c0FK5Fpun4jqc2d2l9IOoLs+7ENFnWnYNEXwJyBIzIdSEs5QhLx2Q1SlnY02HF97wbTSTb4x6PQ8ON2YVH6Py4k+35k1q8yebfnMMOAKApoZK8A6WiKI2f1u8DgZ29cxfZZPOfXcEL80aL1E/wCcysmH4CHBBgSSsBk2uPZN4bnjwcQoLv0Jcv2hjUwzyZUWqu+LeAbSeW4OlwzZrptmhuoObvXd7/rFBBmcB80+hHJl7m6dwISpjhfW/UOiJ/gNysZiFWK2hvMqdkJwqZLe/OTp2DKECxntvd+xi3WK8+Vf3ibCBO0ynjY5YgIViPABgXL8tB1ewqgMqxxhGGex0="
git:
  clone: false

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
#We need it because otherwise Travis CI injects an awkward './gradlew assemble' step into the CI workflow
#We want to control and decide what Gradle tasks are executed
install:
  - true

before_script:
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
        git config --global user.email "SvcReleaserBackend@yoomoney.ru"
        git config --global user.name "yoomoney-robot"
        echo $GIT_KEY | openssl base64 -A -d >> ~/.ssh/git_key
        export ORG_GRADLE_PROJECT_signingKey=$(echo $PUBLISH_GPG_KEY | openssl base64 -A -d)
        chmod 400 ~/.ssh/git_key
        eval `ssh-agent -s`
        echo "echo $GIT_KEY_PASSPHRASE" >> $HOME/passphrase
        chmod 700 $HOME/passphrase
        export DISPLAY=":0.0"
        cat ~/.ssh/git_key | SSH_ASKPASS="$HOME/passphrase" ssh-add -
        git clone --depth=50 --branch=$TRAVIS_BRANCH git@github.com:$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        cd $TRAVIS_REPO_SLUG
        git checkout -f $TRAVIS_BRANCH
        export GIT_PRIVATE_SSH_KEY_PATH=~/.ssh/git_key
    fi
  - |
    if [ $TRAVIS_BRANCH != "master" ]; then
        git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        cd $TRAVIS_REPO_SLUG
        git checkout -f $TRAVIS_BRANCH
    fi

if: commit_message !~ /(\[Gradle Release Plugin\])/

jobs:
  include:
    - stage: build
      script:
        - ./gradlew -b build.gradle clean build test checkCoverage publish --info --stacktrace --refresh-dependencies
    - stage: release
      if: branch = master
      script:
        - |
          ./gradlew -b build.gradle preRelease --info  --stacktrace --refresh-dependencies -D"gradle.publish.key"=$GRADLE_PUBLISH_KEY -D"gradle.publish.secret"=$GRADLE_PUBLISH_SECRET
          if [ $? != 0 ]
          then
           exit 1
          fi
          ./gradlew -b build.gradle release --info --stacktrace --refresh-dependencies -D"gradle.publish.key"=$GRADLE_PUBLISH_KEY -D"gradle.publish.secret"=$GRADLE_PUBLISH_SECRET

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
